"""Initial migration

Revision ID: 25608eea506d
Revises: 
Create Date: 2025-08-23 00:30:46.632268

"""
# ============================================================================
# INITIAL DATABASE MIGRATION
# ============================================================================
# This migration establishes the initial database schema for the Pythonic app
# It adds the bio field to the user table for user profile information

# Alembic operation imports for database schema modifications
from alembic import op
import sqlalchemy as sa


# ============================================================================
# MIGRATION METADATA
# ============================================================================

# Revision identifiers, used by Alembic for version control
revision = '25608eea506d'
down_revision = None  # This is the first migration
branch_labels = None
depends_on = None


# ============================================================================
# MIGRATION OPERATIONS
# ============================================================================

def upgrade():
    """
    Upgrade database schema to add bio field to user table.
    
    This migration adds a new 'bio' column to the 'user' table,
    allowing users to provide biographical information in their profiles.
    The field is nullable, so existing users won't be affected.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add bio column for user profile information
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade database schema by removing bio field from user table.
    
    This migration removes the 'bio' column from the 'user' table,
    reverting the changes made in the upgrade function.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Remove bio column from user table
        batch_op.drop_column('bio')
    # ### end Alembic commands ###
