"""Rename name to title in Course model

Revision ID: 305987e854e1
Revises: 25608eea506d
Create Date: 2025-08-26 17:31:46.216932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305987e854e1'
down_revision = '25608eea506d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we need to use a different approach since it doesn't support
    # ALTER COLUMN SET NOT NULL directly
    
    # Drop the temporary table if it exists
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_course')
    
    # Create a temporary table with the new schema
    op.create_table(
        '_alembic_tmp_course',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('icon', sa.String(length=20), nullable=False, server_default='default_icon.png'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Copy data from old table to new table
    op.execute('INSERT INTO _alembic_tmp_course (id, title, description, icon) SELECT id, COALESCE(title, name), description, icon FROM course')
    
    # Drop the old table
    op.drop_table('course')
    
    # Rename the temporary table to the original name
    op.rename_table('_alembic_tmp_course', 'course')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the name column with nullable=True
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=True))
    
    # Copy data from title to name
    op.execute('UPDATE course SET name = title')
    
    # Now make the name column NOT NULL
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('name', nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
