"""Add date_posted to Course model simple

Revision ID: bc40889515f6
Revises: 305987e854e1
Create Date: 2025-08-30 01:05:31.362870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc40889515f6'
down_revision = '305987e854e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))
        # Remove the problematic unique constraint creation
        # batch_op.create_unique_constraint(None, ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('course', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###
