"""Add slug to Course model

Revision ID: fc362fcdb5aa
Revises: bc40889515f6
Create Date: 2025-08-30 03:07:36.853682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc362fcdb5aa'
down_revision = 'bc40889515f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=False, server_default='default-slug'))
        # Remove problematic constraints - SQLite requires constraint names
        # batch_op.create_unique_constraint(None, ['slug'])
        # batch_op.create_unique_constraint(None, ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='unique')
        # batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###